name: emaktab_autologin
description: eMaktab Auto Login
publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  file_picker: ^8.0.0
  path_provider: ^2.1.2

flutter:
  uses-material-design: true